version: '3'

services:
  db:
    image: mongo:4.1
    volumes:
      - data-db:/data/db
    ports:
      - "27017:27017"

  search:
    build: ./elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - data-search:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  data-db:
  data-search:
